https://awstip.com/amazon-polly-for-beginners-c51bf67d5a93
https://docs.aws.amazon.com/polly/latest/dg/get-started-what-next.html


---------
https://github.com/amna2024/Portfolio/blob/main/AWS%20Projects/AWSpolly-text-speech-converter/Lambda-handlar.py
https://www.linkedin.com/pulse/transforming-text-speech-my-aws-polly-project-lambda-python-sohail-x5kqf/
------

amazon polly lambda function code https://github.com/ran-isenberg/aws-text-to-speech/blob/main/service/handlers/consumer.py

amazon polly implementaion https://www.ranthebuilder.cloud/post/serverless-empowers-accessibility-convert-text-to-speech-with-amazon-polly


https://agatakubat.pl/make-your-pi-speak-with-text-to-speech-fom-amazon-polly/
